---
title: "TidyTemplate"
date: 2021-01-05
output: html_output
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(countrycode)
library(glue)

```

# Load the weekly Data

```{r Load}
tt <- tt_load("2021-01-05")
```

```{r Readme, eval = interactive()}
tt
```

```{r Glimpse}
tt %>% 
  map(glimpse) 

transit_Cost <- tt$transit_cost %>%
  filter(!is.na(e)) %>% 
  mutate_at(vars(start_year, end_year), as.numeric) %>% 
  mutate(country_code = ifelse(country == "UK", "GB", country),
         country = countrycode(country_code, "iso2c", "country.name"),
         real_cost = parse_number(real_cost),
         tunnel_per = tunnel / length,
         rr = ifelse(rr, "Railroad", "Not Railroad"))


```

```{r}
transit_Cost %>% 
  count(city, country, sort = TRUE)

transit_Cost %>% 
  filter(country == "United States") %>%
  mutate(line = fct_reorder(line, year)) %>% 
  ggplot(aes(xmin = start_year, xmax = end_year, y = line, color = city, size = real_cost)) +
  geom_errorbarh(height = .1) +
  labs(x = "year",
       y = "",
       color = "City")

transit_Cost %>%
  filter(!is.na(cost_km_millions),
         tunnel_per == 1) %>%
  mutate(country = fct_lump(country, 10)) %>%
  add_count(country) %>% 
  mutate(country = glue("{ country } ({ n })"),
         country = fct_reorder(country, cost_km_millions)) %>%
  ggplot(aes(cost_km_millions, country)) +
  geom_boxplot() +
  scale_x_continuous(labels = dollar) +
  labs(x = "Cost / KM (Millions of USD)")

transit_Cost %>%
  filter(!is.na(cost_km_millions),
         tunnel_per == 1) %>%
  mutate(country = fct_lump(country, 10)) %>%
  add_count(country) %>% 
  mutate(country = glue("{ country } ({ n })"),
         country = fct_reorder(country, cost_km_millions)) %>%
  ggplot(aes(cost_km_millions, country, fill = rr)) +
  geom_boxplot() +
  scale_x_continuous(labels = dollar) +
  labs(x = "Cost / KM (Millions of USD)")

```

```{r}
transit_Cost %>% 
  filter(!is.na(cost_km_millions),
         tunnel_per == 1,
         country == "China") %>%
  mutate(city = fct_lump(city, 10)) %>%
  add_count(city) %>% 
  mutate(city = glue("{ city } ({ n })"),
         city = fct_reorder(city, cost_km_millions)) %>%
  ggplot(aes(cost_km_millions, city)) +
  geom_boxplot() +
  scale_x_continuous(labels = dollar) +
  labs(x = "Cost / KM (Millions of USD)") +
  expand_limits(x = 0)

transit_Cost %>% 
  filter(country == "China",
         city == "Shanghai",
         !is.na(start_year),
         !is.na(end_year)) %>%
  mutate(line = fct_reorder(line, year)) %>% 
  mutate_at(vars(start_year, end_year), as.numeric) %>% 
  ggplot(aes(xmin = start_year, xmax = end_year, y = line, color = city, size = real_cost)) +
  geom_errorbarh(height = .1) +
  labs(x = "year",
       y = "",
       color = "City")

transit_Cost %>% 
  filter(tunnel_per == 1,
         end_year <= 2020,
         country == "China") %>% 
  group_by(year = (year %/% 5) * 5) %>% 
  summarize(median_cost_km = median(cost_km_millions, na.rm = TRUE),
            n = n()) %>% 
  ggplot(aes(year, median_cost_km)) +
  geom_line() +
  geom_point

transit_Cost %>% 
  filter(tunnel_per == 1,
         end_year <= 2020,
         country == "China") %>% 
  mutate(year = (year %/% 5) * 5,
         city = fct_lump(city, 5)) %>% 
  ggplot(aes(year, cost_km_millions, group = year)) +
  geom_boxplot(outlier.size = -1) +
  geom_jitter(aes(color = city), height = 0, width = 1) +
  expand_limits(y = 0) +
  labs(y = "Cost / km (Real USD, Millions)",
       x = "Year",
       title = "Cost distribution in China") 
```

```{r}
transit_Cost %>% 
  filter(tunnel_per == 1,
         end_year <= 2020,
         country == "China") %>% 
  mutate(city = fct_lump(city, 4)) %>% 
  ggplot(aes(stations / length,  cost_km_millions, size = length, color = city)) +
  geom_point() +
  expand_limits(x = 0, y = 0) +
  labs(x = "Stations / km",
       y = "Cost / km")
```


```{r}

```


