---
title: "TidyTemplate"
date: 2021-01-09
output: html_output
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)

```

```{r Load}
tt <- tt_load("2020-07-07")
```

```{r Readme, eval = interactive()}
tt
```


```{r Glimpse}
tt %>% 
  map(glimpse)

coffee_ratings <- tt$coffee_ratings %>% 
  filter(total_cup_points > 0) %>%
  mutate(coffee_id = row_number())



```

```{r}
count_sorted <- partial(count, sort = TRUE)

coffee_ratings %>% 
  count_sorted(species)

coffee_lumped <- coffee_ratings %>%
  filter(!is.na(variety)) %>% 
  mutate(variety = fct_lump(variety, 12))
  
coffee_lumped %>%
  mutate(variety = fct_reorder(variety, total_cup_points)) %>% 
  ggplot(aes(total_cup_points, variety)) +
  geom_boxplot()

coffee_lumped %>%
  ggplot(aes(total_cup_points, fill = variety)) +
  geom_histogram(binwidth = 2) +
  facet_wrap(~ variety, scale = "free_y") +
  theme(legend.position = "none")
```

```{r}
coffee_ratings %>%
  summarize(across(everything(), ~ mean(!is.na(.)))) %>% 
  pivot_longer(everything()) %>% 
  View()

coffee_ratings %>% 
  count_sorted(producer)

coffee_ratings %>% 
  count_sorted(company)

coffee_ratings %>% 
  count_sorted(color)

coffee_ratings %>% 
  count_sorted(country = fct_lump(country_of_origin, 12)) %>% 
  filter(!is.na(country)) %>%
  mutate(country = fct_reorder(country, n)) %>% 
  ggplot(aes(n, country)) +
  geom_col() 
  
coffee_ratings %>%
  filter(!is.na(country_of_origin)) %>% 
  mutate(country = fct_lump(country_of_origin, 12),
         country = fct_reorder(country, total_cup_points)) %>% 
  ggplot(aes(total_cup_points, country)) +
  geom_boxplot()

```

```{r}
library(ggridges)

coffee_metrics <- coffee_ratings %>% 
  select(coffee_id, total_cup_points, variety, company, 
         country_of_origin,
         altitude_mean_meters,
         aroma:moisture) %>% 
  pivot_longer(aroma:cupper_points, names_to = "metric", values_to = "value")

coffee_metrics %>% 
  mutate(metric = fct_reorder(metric, value)) %>% 
  ggplot(aes(value, metric)) + 
  geom_density_ridges()

coffee_metrics %>% 
  group_by(metric) %>% 
  summarize(average = mean(value),
            sd = sd(value)) %>% 
  arrange(desc(average))
```

```{r}
library(widyr)
library(ggraph)
library(igraph)
library(tidytext)

correlations <- coffee_metrics %>% 
  pairwise_cor(metric, coffee_id, value, sort = TRUE)

correlations %>% 
  head(50) %>% 
  graph_from_data_frame() %>% 
  ggraph() +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), repel = TRUE)

coffee_metrics %>%
  filter(!metric %in% c("sweetness", "clean_cup", "uniformity")) %>% 
  group_by(metric) %>% 
  mutate(centered = value - mean(value)) %>%
  ungroup() %>% 
  widely_svd(metric, coffee_id, centered) %>%
  mutate(metric = reorder_within(metric, value, dimension)) %>% 
  filter(dimension <= 4) %>% 
  ggplot(aes(value, metric)) +
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~ dimension, scale = "free_y")

coffee_metrics %>%
  filter(!metric %in% c("sweetness", "clean_cup", "uniformity")) %>% 
  widely_svd(metric, coffee_id, value) %>%
  mutate(metric = reorder_within(metric, value, dimension)) %>% 
  filter(between(dimension, 2, 5)) %>% 
  ggplot(aes(value, metric)) +
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~ dimension, scale = "free_y")
```

```{r}
coffee_ratings %>%
  filter(altitude_mean_meters < 10000,
         altitude > 1) %>%
  mutate(altitude_mean_meters = pmin(altitude_mean_meters, 3000)) %>% 
  ggplot(aes(altitude_mean_meters, total_cup_points)) +
  geom_point() +
  geom_smooth(method = "lm")

coffee_metrics %>% 
  filter(altitude_mean_meters < 10000) %>%
  mutate(altitude_mean_meters = pmin(altitude_mean_meters, 3000)) %>%
  mutate(km = altitude_mean_meters / 1000) %>% 
  group_by(metric) %>% 
  summarize(correlation = cor(altitude_mean_meters, value),
            model = list(lm(value ~ km))) %>% 
  mutate(tidied = map(model, tidy, conf.int = TRUE)) %>% 
  unnest(tidied) %>% 
  filter(term == "km") %>%
  ungroup() %>% 
  mutate(metric = fct_reorder(metric, estimate)) %>% 
  ggplot(aes(estimate, metric, color = p.value < 0.05)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.1) +
  labs(y = "Evaluation of coffee",
       x = "Each km of altitude contributes this much to score (95% confidence interval)")
```

